name: frag10
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch
  - cudatoolkit=11.6
  - dgl
  - torchmetrics
  - networkx
  - tqdm
  - jupyterlab
  - ipywidgets
  - cctbx-base
  - rdkit
  - pynndescent
  - umap-learn
  - scikit-learn
  - seaborn
  - numpy>=1.20
  - pip:
    - pdbecif
    - torchani
