name: frag
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch
  - dgl
  - torchmetrics
  - networkx
  - tqdm
  - cctbx-base
  - rdkit
  - pynndescent
  - umap-learn
  - scikit-learn
  - numpy>=1.20
  - pip:
    - pdbecif
    - torchani
