name: frag
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch
  - dgl
  - torchmetrics
  - networkx
  - tqdm
  - cctbx-base
  - rdkit
  - pip:
    - pdbecif
    - torchani